app/api/entity/user.go
app/api/usecase/user/interactor.go
app/api/usecase/user/interactor_test.go

- If the user name contains characters like dots, the creation of the secret fails

use the user name slug as name for ssh keys secrets

---

app/api/infrastructure/k8s/usertools.go

The resource name for the user-tools contains the username slug but the API is using the username.
It fails if the user name contains dots like: john.doe

use the username slug to stop the user tools

---

app/api/infrastructure/k8s/usertools.go

This PR fixes a bug that produces kubernetes "usertools" resources are being generated without giteaOauth2Setup configuration.
To test this on a running KDL local dev environment:
```
$ ./kdlctl.sh build
$ ./kdlctl.sh deploy
```
Enjoy!

fix(app): typo in app/api/infrastructure/k8s/usertools.go

---

vscode/Dockerfile
vscode/entrypoint.sh

VS Code is missing a parameter both in the Dockerfile and in the entrypoint.sh file to declare where the extensions are going to be installed

fix(vscode): Install extensions declaring dir

---

vscode/Dockerfile
vscode/entrypoint.sh

We need to change the VS Code extensions and entrypoint.sh files location out of coder home, given that this folder is going to be replaced with a persistent volume when the container is created (see helm statetfulset template)

fix(vscode): Change installation files out of coder home

---

jupyter-gpu/Dockerfile
jupyter-gpu/requirements.txt

The solution is to upgrade image base to `nvidia/cuda:11.0.3-cudnn8-runtime-ubuntu18.04` and the following libraries:
* tensorflow: 2.0.0b1 -> 2.7.0-rc1
* pytorch-lightning: 1.3.5 -> 1.3.8

fix(jupyter-gpu): tensorflow==2.0.0b1 python library cannot be installed anymore

---

helm/kdl-server/templates/_helpers.tpl
helm/kdl-server/templates/app/ingress.yaml
helm/kdl-server/templates/drone/configmap.yaml
helm/kdl-server/templates/drone/ingress.yaml
helm/kdl-server/templates/drone/runner-deployment.yaml
helm/kdl-server/templates/gitea/ingress.yaml
helm/kdl-server/templates/gitea/statefulset.yaml
helm/kdl-server/values.yaml
scripts/kdlctl/cmd_deploy.sh
scripts/kdlctl/cmd_login.sh

This feature will allow:
* A custom previous manually deployed custom secret can be specified when tls is enabled if integrated cert manager resources are disable
* A custom CA certificate can be added in case the custom tls secret contains a self-signed certificate.This is needed for Gitea and Drone Runner containers in order they could accept the certificates included in the above secret.

feat(helm): Allow use custom TLS secret

---

scripts/kdlctl/cmd_deploy.sh

Current value for `kdlServer.image.tag` and `backup.image.tag` is not being set to "latest" in `cmd_deploy.sh` script.

fix(kdlctl): Set the right tag value for kdl-server in local dev

---

helm/kdl-server/templates/app/ingress.yaml
helm/kdl-server/values.yaml

KdlApp ingress timeout values are now under `.Values.kdlApp.ingress` dictionary.

fix(helm): KdlApp ingress timeout values

---

helm/kdl-server/values.yaml

Changes `kdlServer.image.version.tag: v0.22.0` to `kdlServer.image.version.tag: 0.22.0` because `konstellation/kdl-server:v0.22.0` Docker image does not exists.

fix(helm): kdlServer.image.version.tag in values.yaml

---

.github/workflows/backup-component-build.yml
.github/workflows/cleaner-component-build.yml
.github/workflows/drone-authorizer-component-build.yml
.github/workflows/gitea-oauth2-setup-component-build.yml
.github/workflows/helm-component.yml
.github/workflows/helm-release.yml
.github/workflows/jupyter-gpu-component-build.yml
.github/workflows/kdl-server-component-build.yml
.github/workflows/mlflow-component-build.yml
.github/workflows/new-release.yml
.github/workflows/project-operator-component-build.yml
.github/workflows/repo-cloner-component-build.yml
.github/workflows/user-tools-operator-component-build.yml
.github/workflows/vscode-component-build.yml

When update the versions files (helm `values.yaml)`) they where updating with the tag (eg. `v.2.1.2`) but we are generating the docker images tagged with the version (eg. `2.1.2`). The new versions of the workflows solves this issue.

fix: update versions in versions files

---

app/ui/package.json

This change fixes the log `Greetings, time traveller. We are in the golden age of prefix-less CSS, where Autoprefixer is no longer needed for your stylesheet.`, which appears when start the UI in development.

fix scss log on development env

---

app/ui/cypress/integration/kubeconfig.spec.ts

During the execution of UI e2e tests on local environment, tests that uses clipboard fail with permission error. This PR grant permissions in this escenario.

test: grant permissions to browser to manage clipboard during headless e2e

---

app/api/infrastructure/graph/generated/generated.go
app/api/infrastructure/graph/schema.resolvers.go
app/graphql/schema.graphqls
app/ui/mock-server/src/index.js
app/ui/mock-server/src/mocks/meMock.js
app/ui/src/Graphql/mutations/setActiveUserTools.ts
app/ui/src/Graphql/mutations/types/SetActiveUserTools.ts
app/ui/src/Graphql/queries/getMe.ts
app/ui/src/Graphql/queries/getUserTools.ts
app/ui/src/Graphql/queries/types/GetMe.ts
app/ui/src/Graphql/queries/types/GetUserTools.ts
app/ui/src/Mocks/entities/user.ts
app/ui/src/Pages/UserSshKey/UserSshKey.tsx

The User field areToolsActive was used to check if user tools were active. With the runtimes changes, the query GetRunningRuntime is the responsible for this, so areToolsActive is not used anymore.
This changes delete this field from graphql schema, and from the API and UI code.

fix(ui): delete areToolsActive references

---

app/api/usecase/user/interactor.go
app/api/usecase/user/interactor_test.go
helm/kdl-server/Chart.yaml

Use username slug instead of username when retrieving the kubeconfig secret.

fix: kubeconfig username slug

---

helm/kdl-server/templates/common/backup-cronjob.yaml
helm/kdl-server/values.yaml

`activeDeadlineSeconds` is hardcoded to 60 (1min) so backup cronjob always fails for big backups.
Now `activeDeadlineSeconds` and `backoffLimit` are set from **values.yaml** file.

fix(helm): backup cronjob activeDeadlineSeconds and backoffLimit values are hardcoded

---

app/api/usecase/user/interactor.go
app/api/usecase/user/interactor_test.go
helm/kdl-server/templates/common/backup-cronjob.yaml
helm/kdl-server/values.yaml
user-tools-operator/helm-charts/usertools/templates/kubeconfig-tpl-configmap.yaml
user-tools-operator/helm-charts/usertools/templates/statefulset.yaml

Cherry pick fixes from v1.0.0 into main
- Kubeconfig-tpl-configmap namming
- Use username-slug to retrieve kubeconfig secrets
- Activate and fix backups

fix: fixes from v1.0.0

---

helm/kdl-server/templates/minio/ingress-minio-console.yml
helm/kdl-server/templates/minio/ingress-minio.yaml

Fixes the credentials issue when trying to access MinIO service through the current ingress.
Added:
* New `minio-console` ingress for MinIO console access
Fixes:
* `minio` ingress now points to the programmatic access service endpoint

FIX: MinIO programatic service access

---

app/ui/src/Pages/Project/components/RuntimeRunner/RuntimeRunner.tsx

Fix the replacement modal that appears when navigates to a projects that already have a runtime running. When trying to replace a runtime with the same runtime, does anything.

fix(ui): avoid replacement modal when navigating to project

---

scripts/kdlctl/cmd_deploy.sh

Added latest tag for mlflow, repoCloner and vscode images to prevent pull the version specified in helm chart values.

fix(local-deploy): set tag for runtime images on local deployment script

---

app/ui/src/Pages/UserKubeconfig/UserKubeconfig.module.scss
app/ui/src/Pages/UserKubeconfig/UserKubeconfig.tsx

Complete the instructions to use the external kubeconfig file in local VSCode. 
closes #744

feat: document full kubeconfig instructions

---

user-tools-operator/helm-charts/usertools/templates/kubeconfig-tpl-configmap.yaml
user-tools-operator/helm-charts/usertools/templates/rbac.yaml
user-tools-operator/helm-charts/usertools/templates/statefulset.yaml
user-tools-operator/helm-charts/usertools/values.yaml

Remove the service account that was tied to the usertools. The service account was being created/deleted with the users tools start/stop. We want that each user has a single serviceAccount that is not tied to the life-cycle of the usertools.
updates #741

feat(usertools-operator): remove serviceaccount

---

app/api/http/main.go
app/api/infrastructure/k8s/interface.go
app/api/infrastructure/k8s/kubeconfig.go
app/api/infrastructure/k8s/mocks_interface.go
app/api/infrastructure/k8s/service_account.go
app/api/infrastructure/k8s/usertools.go
app/api/usecase/user/interactor.go
app/api/usecase/user/interactor_test.go
app/api/usecase/user/interface.go
app/api/usecase/user/mocks_interface.go

With this commit, the KdlApp is the responsible for generating and mantaining the ServiceAccounts for the users. It checks and generate the ServiceAccounts at application startup.
When generating the kubeconfig for the users, use the user ServiceAccount to build the kubeconfig file live, instead of taking them from the kubeconfig secret.
updates #741

feat(api): create service accounts from app

---

app/api/usecase/user/interactor_test.go

Fixed a linting error in a test. The linter compalins about the blank line between a comment and the first statement.

fix(api): fix golang lint

---

helm/kdl-server/templates/app/deployment.yaml
helm/kdl-server/templates/drone/runner-deployment.yaml
helm/kdl-server/templates/drone/statefulset.yaml
helm/kdl-server/templates/gitea/statefulset.yaml
helm/kdl-server/templates/knowledge-galaxy/deployment.yaml
helm/kdl-server/templates/mongo/statefulset.yaml
helm/kdl-server/templates/postgres/statefulset.yaml
helm/kdl-server/templates/project-operator/deployment.yaml
helm/kdl-server/templates/user-tools-operator/deployment.yaml
helm/kdl-server/values.yaml

NodeSelector, Affinity and Toleration annotations added to the following chart components:
* drone
* droneRunner
* gitea
* knowledgeGalaxy
* kdlServer
* minio (just added default values because original MinIO chart already allows for this)
* mongodb
* postgres
* projectOperator (just for the operator pod itself) 
* userToolsOperator (just for the operator pod itself)
Closes #757

[Feature]: Helm chart advanced pod scheduling

---

app/ui/cypress/integration/kubeconfig.spec.ts
app/ui/src/Components/SettingsMenu/SettingsMenu.tsx
app/ui/src/Components/SettingsMenu/__snapshots__/SettingsMenu.test.tsx.snap
app/ui/src/Components/UserPageHeader/UserPageHeader.module.scss
app/ui/src/Components/UserPageHeader/UserPageHeader.tsx
app/ui/src/Pages/UserKubeconfig/UserKubeconfig.module.scss
app/ui/src/Pages/UserKubeconfig/UserKubeconfig.tsx
app/ui/src/Pages/UserSshKey/UserSshKey.module.scss
app/ui/src/Pages/UserSshKey/UserSshKey.tsx

When navigates to kubeconfig or user ssh key pages, the left navigation bar disappears and it's annoying having to open again the project.
Since we can't keep the side bar because these routes don't belong to any project,  adding a 'go to last page' button on these pages makes it more usable.

fix(ui): allow back navigation from setting pages

---

.github/workflows/kdl-server-component-build.yml

The UI E2E tests are not being executed on CI. This tests are more reliable than unit tests, so this change adds one step on the workflow to execute them.

fix(ci): add UI e2e tests to workflow

---

app/api/http/main.go
app/api/infrastructure/k8s/interface.go
app/api/infrastructure/k8s/mocks_interface.go
app/api/infrastructure/k8s/service_account.go
app/api/usecase/user/interactor.go
app/api/usecase/user/interactor_test.go
app/api/usecase/user/interface.go
app/api/usecase/user/mocks_interface.go

Contemplates that, when a user is removed from the system, his userServiceAccount is deleted too on the startup synchronization.
Closes #752

fix(api) delete userServiceAccount on user remove

---

app/api/go.mod
app/api/go.sum
app/api/pkg/sshhelper/generator.go

Because the rsa sha1 have been deprecated by github we change to new type of key generation ED25519
Closes #760

Fix(api)/ssh key generation

---

.github/workflows/backup-component-build.yml
.github/workflows/cleaner-component-build.yml
.github/workflows/drone-authorizer-component-build.yml
.github/workflows/gitea-oauth2-setup-component-build.yml
.github/workflows/helm-component.yml
.github/workflows/helm-release.yml
.github/workflows/jupyter-gpu-component-build.yml
.github/workflows/jupyter-kernelspecs-component-build.yml
.github/workflows/kdl-server-component-build.yml
.github/workflows/mlflow-component-build.yml
.github/workflows/new-release.yml
.github/workflows/project-operator-component-build.yml
.github/workflows/repo-cloner-component-build.yml
.github/workflows/user-tools-operator-component-build.yml
.github/workflows/vscode-component-build.yml

We need to update the workflows version to the last release which fixes a problem with the monorepo-tagger-action in this commit https://github.com/intelygenz/monorepo-tagger-action/commit/01122ed406e84cefe26810b061ee6287e2c2aa81

ci: update workflows version

---

app/api/usecase/user/interactor.go

When kubeConfig text is sent to the front, the api send it with a newLine char at the beginning.
Closes #772

fix(api) remove a newLine char from beginning of kubeConfig text

---

user-tools-operator/helm-charts/usertools/templates/statefulset.yaml

This PR modifies the user-tools-operator statefullset definition to allow the Jupyter container to pass Jupyter Kernels the name of the shared PVC via the `KERNEL_SHARED_VOLUME_NAME` environment variable.
Must be merged after #783 
Related #782

fix: pass Jupyter kernels the name of the shared volume PVC from user-tools

---

.github/workflows/helm-release.yml
helm/kdl-server/crds/user-tools-operator-crd.yaml
helm/kdl-server/templates/app/configmap.yaml
helm/kdl-server/templates/minio/ingress-minio-console.yml
helm/kdl-server/templates/minio/ingress-minio.yaml

This introduces the following changes:
* MinIO ingresses now use the right TLS secret name
* Introduced **TOOLKIT_TLS_SECRET_NAME** variable that passes to kdlApp the name of the TLS Secret to use in user-tools.
**WARNING:** This PR introduces a breaking change because helm/kdl-server/crds/user-tools-operator-crd.yaml has been changed and needs to be manually deployed before apply the release containing these changes.
Complements #800 and #802

fix: pass the right tls secret name to MinIO and user-tools ingresses

---

app/api/infrastructure/config/config.go
app/api/infrastructure/k8s/kdlproject.go
app/api/infrastructure/k8s/usertools.go

This allows tha KDL App to pass the tls secret name to the user-tools through their UserTools resources
Complements #800 and #801

fix: pass user-tools the name of the tls secret

---

user-tools-operator/helm-charts/usertools/templates/ingress.yaml
user-tools-operator/helm-charts/usertools/values.yaml

This PR introduces the following changes
* Remove `Values.ingress.type` and add `.Values.ingress.annotations`
* Add default ingress annotations
BREAKING_CHANGE: Requires update *usertools.kdl.konstellation.io* CRD
in *kdl-server* chart to fit the changes in `values.yaml`
Merge before #806 and #807
related #804

feature: pass ingress annotations from values.yaml

---

app/api/infrastructure/config/config.go
app/api/infrastructure/k8s/kdlproject.go
app/api/infrastructure/k8s/usertools.go

This PR introduces the follwing changes:
* Allow App to pass to the generated user-tools the ingress annotations received from the chart through their `userTools` resources.
Do not merge before #806
Related #804

feature: pass user-tools ingress annotations through userTools k8s resources

---

app/api/templates/basic/.drone.yml.tmpl

This PR fixes an issue when a kdlproject is created.
The Drone `minio-key-id` and `minio-secret` now reference the kubernetes secret that is being generated by the App for the project.

fix: mlflow secret in app/api/templates/basic/.drone.yml.tmpl

---

ct.yaml
helm/kdl-server/Chart.lock
helm/kdl-server/Chart.yaml
helm/kdl-server/values.yaml

This PR fixes the issue with the Jupyter Enterprise Gateway Helm chart repo that was removed from artifacthub.io.
This will merge the hotfix into branch `release-v2.1`

fix: jupyter enterprise gateway dependency repository (release-v2.1)

---

ct.yaml
helm/kdl-server/Chart.lock
helm/kdl-server/Chart.yaml
helm/kdl-server/values.yaml

This PR fixes the issue with the Jupyter Enterprise Gateway Helm chart repo that was removed from artifacthub.io.
This will merge the hotfix into branch `release-v3.0`

 fix: jupyter enterprise gateway dependency repository (release-v3.0)

---

ct.yaml
helm/kdl-server/Chart.lock
helm/kdl-server/Chart.yaml
helm/kdl-server/values.yaml

This PR fixes the issue with the Jupyter Enterprise Gateway Helm chart repo that was removed from artifacthub.io.
This will merge the hotfix into `main` branch

fix: jupyter enterprise gateway dependency repository (main) 

---

.github/workflows/helm-release.yml
README.md
helm/kdl-server/crds/user-tools-operator-crd.yaml

This PR adds the `status` field to the user-tools-operator-crd
Introduces a BREAKING CHANGE as **usertools.kdl.konstellation.io** CRD needs to be manually deployed

fix: user-tools-operator-crd.yaml had not status field

---

helm/kdl-server/templates/app/oauth2-proxy-configmap.yaml
user-tools-operator/helm-charts/usertools/templates/oauth2-proxy-configmap.yaml

This PR fixes the following error:
oauth2-proxy "Named cookie not found" error when TLS is disabled.
Affected components:
* user-tools-operator
* kdlApp

fix: oauth2-proxy named cookie not found

---

user-tools-operator/helm-charts/usertools/templates/oauth2-proxy-configmap.yaml

This PR sets the `cookie_samesite` value to "lax" in oauth2-proxy configuration when tls is disabled.

fix(user-tools-operator): named cookie not found error when tls is disabled

---

helm/kdl-server/templates/drone/runner-deployment.yaml

This will fix the `runner-deployment.yaml` template file. Conditional blocks were not being properly used.

fix: runner-deployment.yaml template

---

app/api/entity/user.go
app/api/entity/user_test.go

Detailed info in #850 
Replace "\_" characters with "-" when generating username slugs. K8s resources that are related to users make use of the username slugs to name the resources. Avoiding "_" in the username slugs fix the resource naming problem.
closes #850

fix: k8s resources fail to create if they contain "_" in the name

---

helm/kdl-server/templates/gitea/init-configmap.yaml

By default Gitea blocks attempts to migrate repositories from private/local networks. So when you are trying to create a project inside KDL and Gitea try to mirror a repository which resolves to a private address then it fails with `ERROR Error creating project: 422 Unprocessable Entity: {"message":"You are not allowed to import from private IPs.", "url": "http://gitea.ia.lab.***.com/api/swagger"}`
Configure Gitea to allow local network addresses by setting `ALLOW_LOCALNETWORKS: true` in its configuration. More info here: https://docs.gitea.io/en-us/config-cheat-sheet/#migrations-migrations
closes #854

feature: configure gitea to allow local networks IPs

---

cleaner/Dockerfile
cleaner/go.mod

Upgrade go mod and Dockerfile to go 1.18 to make use of workspaces.
This is part of [this issue](https://github.com/konstellation-io/kdl-server/issues/848)

fix(cleaner): Update to 1.18 and add Go workspaces

---

helm/kdl-server/templates/app/configmap.yaml

Add common labels to the api configmap to be used when creating serviceaccounts
This is part of https://github.com/konstellation-io/kdl-server/issues/848

feat(helm): Add common labels

---

backup/files/backup-script.sh

This fixes the problem cleaning up the backup temporary files when a volume is mounted on `/backup` folder.

fix: backup cleanup

---

user-tools-operator/helm-charts/usertools/templates/_helpers.tpl
user-tools-operator/helm-charts/usertools/templates/ingress.yaml
user-tools-operator/helm-charts/usertools/values.yaml

This PR adds the following:
* ingress `spec.tls.secretName` will have an autogenerated value when `tls.secretName` is not provided from values.

feat(user-tools-operator): autogenerate ingress tls secret name when tls.secretName is not provided from values

---

app/api/infrastructure/config/config.go
app/api/infrastructure/k8s/usertools.go

This PR adds the following:
* `spec.tls.secretName` won't be defined if `TOOLKIT_TLS_SECRET_NAME` env variable is undefined.
Notice that **undefined** does not mean that the `TOOLKIT_TLS_SECRET_NAME` env variable contains the empty string value ("")

feat(app): not set 'spec.tls.secretName' on UserTools when the 'TOOLKIT_TLS_SECRET_NAME' env var is undefined

---

app/api/infrastructure/config/config.go
app/api/infrastructure/k8s/usertools.go

This PR adds the posibillity of defining `spec.ingress.className` to `UserTools` generated resources.

feat(app): add `spec.ingress.className` field to generated UserTools

---

.gitignore
README.md
helm/kdl-server/crds/user-tools-operator-crd.yaml
helm/kdl-server/templates/app/configmap.yaml
helm/kdl-server/templates/app/ingress.yaml
helm/kdl-server/templates/drone/ingress.yaml
helm/kdl-server/templates/gitea/ingress.yaml
helm/kdl-server/templates/minio/ingress-minio-console.yml
helm/kdl-server/templates/minio/ingress-minio.yaml
helm/kdl-server/values.yaml

This PR adds `spec.ingressClassName` field to all ingress component definitions.
BREAKING CHANGE: `values.yaml` and `usertools.kdl.konstellation.io` CRD have been updated
* `<component>.ingress.annotations.kubernetes.io/ingress.class: "nginx"` annotations removed in favour of `<component>.ingress.className`
* updated usertools.kdl.konstellation.io CRD

feat(helm): add ingressClassName to all component ingresses

---

.github/workflows/project-operator-component-build.yml

* Automatic version bumping of project-operator was not being performed properly

ci(project-operator): fix component_helm_tag value in .github/workflows/project-operator-component-build.yml

---

helm/kdl-server/CHART.md
helm/kdl-server/values.yaml

* Manually bump projectOperator.manager.image.tag  to 0.15.0 because the respective workflow was not working as expected (now fixed).

fix(helm): manually bump projectOperator.manager.image.tag 

---

helm/kdl-server/templates/project-operator/rbac.yaml

* project-operator had insufficient permissions for managing ingress resources when rbac is enabled in the kube-apiserver

fix(helm): allow project-operator to manage ingress resources

---

helm/kdl-server/CHART.md
helm/kdl-server/values.yaml

* Due an error on automatic release process the next **user-tools-operator** release was not published, so this has to be manually bumped. The new release (v0.24.0) has already been manually pushed to Dockerhub.
* Due an error on automatic release process the next **kdl-backup** release was not published, so this has to be manually bumped. The new release (v0.22.0) has already been manually pushed to Dockerhub.

fix(helm): manually bump user-tools-operator version 

---

scripts/helmfile/values/kdl-local/values.yaml.gotmpl
scripts/helmfile/values/mongodb-database/values.yaml.gotmpl

This PR fixes the way we create users and assign roles to them in the local development environment:
User list:
* **kdl** (application user):
* database: `kdl`
* attached roles: `readWrite` (builtin)
* **admin** (mongodb admin user):
* database: `admin`
* attached roles: `root` (builtin)

chore(local-dev): fix mongodb users and roles

---

project-operator/helm-charts/kdlproject/templates/mlflow/configmap.yml
project-operator/helm-charts/kdlproject/templates/mlflow/deployment.yml
project-operator/helm-charts/kdlproject/templates/mlflow/secret.yml
project-operator/helm-charts/kdlproject/values.yaml

This PR contains the following changes:
* Fix: receive `MLFLOW_S3_ENDPOINT_URL` env variable value from `values.yaml` instead of accessing to `tools-secret` kubernetes secret directly

fix(project-operator): receive MLFLOW_S3_ENDPOINT_URL from values

---

app/api/infrastructure/k8s/kdlproject.go
app/api/infrastructure/templates/templating.go

`spec.minio.endpointURL` is now passed to generated KDLProjects

feat(app): pass spec.minio.endpointURL to generated KDLProjects

---

helm/kdl-server/templates/app/deployment.yaml

This PR fixes an issue when the KDL Server app tries to create a project's bucket and folders on MinIO.

fix(helm): pass kdl-server secret to kdl-app container

---

backup/README.md
backup/restore-pod.yaml

* refactor `restore-pod.yaml` to fit the new configmap and secret requirements

chore(backup): update restore-pod.yaml to fit new configmap and secret requirements

---

user-tools-operator/helm-charts/usertools/templates/ingress.yaml
user-tools-operator/helm-charts/usertools/templates/rbac.yaml
user-tools-operator/helm-charts/usertools/templates/statefulset.yaml
user-tools-operator/helm-charts/usertools/values.yaml

* Oauth2 setup configmap and secret are now being received from values.yaml

fix(user-tools-operator): receive oauth2 setup configmap and secrets from values

---

app/api/.golangci.yml
app/api/infrastructure/config/config.go
app/api/infrastructure/k8s/usertools.go

Pass generated *UserTools* the following fields:
```yaml
spec:
giteaOauth2Setup:
giteaAdminSecret: <string>
giteaOauth2Configmap: <string>
```

feat(app): pass oauth2 config to generated usertools

---

project-operator/helm-charts/kdlproject/templates/_helpers.tpl

Project Operator:
* Generate `spec.tls.secretName` value on mlflow ingress when `.Values.mlflow.ingress.tls.secretName` is not defined

fix(project-operator): generate spec.tls.secretName value on mlflow

---

helm/kdl-server/CHART.md
helm/kdl-server/crds/project-operator-crd.yaml
helm/kdl-server/templates/app/configmap.yaml
helm/kdl-server/values.yaml

**WHY**
kdl-server app needs to retrieve pod scheduling options from char's values
**WHAT**
Added environment variables to `kdl-server` configmap in order to pass kdl-app the kdlproject's pods scheduling strategies.
BREAKING CHANGE: kdlprojects.project.konstellation.io CRD has been updated

feat(helm): add nodeSelector, affinity, and tolerations env variables for kdlproject's mlflow and filebrowser

---

ct.yaml
helm/kdl-server/CHART.md
helm/kdl-server/Chart.lock
helm/kdl-server/Chart.yaml
helm/kdl-server/README.md
helm/kdl-server/crds/user-tools-operator-crd.yaml
helm/kdl-server/templates/app/configmap.yaml
helm/kdl-server/values.yaml
scripts/helmfile/helmfile.lock
scripts/kdlctl/cmd_deploy.sh

**WHY**
Jupyter Notebook is being removed from KDL Server
**WHAT**
Removed all Jupyter Notebook references and Jupyter Enterprise Gateway dependency from the chart.
**BREAKING CHANGE**
* *usertools.kdl.konstellation.io* CRD has been updated, so it must be manually applied before upgrading the chart
* *Jupyter Enterprise Gateway* dependency has been removed

refactor(helm): remove jupyter enterprise gateway

---

app/api/infrastructure/repository/user.go
app/api/usecase/user/interactor_test.go
app/api/usecase/user/interactor_users_sync.go
app/api/usecase/user/interactor_users_sync_internal_test.go
app/api/usecase/user/interface.go
app/api/usecase/user/mocks_interface.go

We need to improve the Gitea users synchronization method to allow Gitea specific behaviours when changing the username.
When a username is modified in Gitea, the default behavior is to remove the current user and create a new user with the updated username.
As we are listening for user modification events, when receiving the user deletion event from Gitea we are logically deleting the user in our database.
When receiving the new user-created event with the new username, the user cannot be created in our db, as we don't allow to add multiple users with the same email, and there is already an existing deleted user with that email.

KNT1-160 - Fix user synchronization when the Gitea username changes.

---

helm/kdl-server/CHART.md
helm/kdl-server/templates/backup/cronjob.yaml
helm/kdl-server/values.yaml

Added following values to be passed to backup CronJob:
```yaml
backup:
concurrencyPolicy: Forbid
failedJobsHistoryLimit: 1
successfulJobsHistoryLimit: 0
startingDeadlineSeconds: 60
backoffLimit: 3
activeDeadlineSeconds: 3600
ttlSecondsAfterFinished: ""
```
Most of the values of the relevant Backup CronJob spec were hard-coded in its template. This caused finished jobs to remain in the cluster as "Completed" or "Failed" pods for a fixed amount of time. If it was necessary for the completed pods to be deleted before that time, the user had to do it manually.
This PR changes the CronJob template making possible to set those values from the chart's _values.yaml_ file
Closes https://intelygenz.atlassian.net/browse/KNT1-206

feat: Pass additional options to backup CronJob (closes KNT1-206)

---

app/api/entity/capabilities.go

Change tolerationSeconds downcasting from int64 to int32
tolerationSeconds implements int32 interface{} not int64

fix(api): [KDL6-34] tolerationSeconds downcasting

---

hack/scripts/kdlctl/cmd_deploy.sh

During deploy script, there was an issue with yq command. Without eval, it was not able to execute the command and set up the EXTERNAL_SERVER_URL environment variable to be used at later stage
Fix an issue to correctly set up EXTERNAL_SERVER_URL environment variable
Closes #

fix(script): amend deploy script to set environment variable

---

app/api/http/main.go
app/api/usecase/user/interactor.go
app/api/usecase/user/interface.go
hack/kdlctl.sh

Restore create  kdladmin on startup until creation of user development is completed.
- [X ] Bugfix
Closes #

fix: restore create admin on kdl app startup

---

hack/scripts/helmfile/values/initial-resources/values.yaml
hack/scripts/helmfile/values/kdl-local/values.yaml.gotmpl

This eliminates the manual steps of creating realm client credentials by passing a default client secret along with the initial configuration.

feat: [KDL6-3] default oauth2 credentials

---

.pre-commit-config.yaml
project-operator/helm-charts/kdlproject/templates/filebrowser/configmap.yml
project-operator/helm-charts/kdlproject/templates/filebrowser/deployment.yml

Added SecurityContext configuration to the Filebrowser deployment template to enforce user and group permissions (UID/GID: 1000). This change ensures proper filesystem access permissions between Filebrowser and the `sharedVolume`.
Filebrowser deployment runs with root privileges (UID/GID: 0), which is not aligned with security best practices and could pose potential security risks. Running as root provides unnecessary elevated permissions and doesn't follow the principle of least privilege.
The deployment now runs with a non-root user (UID/GID: 1000) through SecurityContext configurations at both pod and container levels, ensuring proper file permissions and access to wirte on …

fix(project-operator): fix filebrowser permissions

---

app/api/http/main.go
app/api/infrastructure/graph/schema.resolvers.go
hack/scripts/helmfile/values/kdl-local/values.yaml.gotmpl

When starting user tools, frontend waits for response from server. If the request takes a long time, it returns 502. It is due to timeout set in http servers, so increasing a bit the numbers.
https://intelygenz.atlassian.net/browse/KDL6-95
Closes #

fix: [KDL6-95] increase timeout in request longer than 10 seconds

---

hack/scripts/helmfile/values/initial-resources/values.yaml

This PR registers the MinIO console as a OIDC client in Keycloak.
- [X ] I have executed the pre-commit hooks locally.
- [X ] The commit message follows our guidelines: https://github.com/konstellation-io/kdl-server/blob/main/CONTRIBUTING.md
- [X ] Feature
No OIDC support for Minio console
Closes #KDL6-228
Keycloak now accepts OIDC request from MinIO
- [X ] No

feat(config): [KDL6-228] minio keycloak client

---

.github/.golangci.yml
app/api/entity/capabilities.go
app/api/infrastructure/k8s/error.go
app/api/infrastructure/k8s/interface.go
app/api/infrastructure/k8s/kdlproject.go
app/api/infrastructure/k8s/kdlproject_test.go
app/api/infrastructure/k8s/kdlusertools.go
app/api/infrastructure/k8s/kdlusertools_test.go
app/api/infrastructure/k8s/mocks_interface.go
app/api/infrastructure/k8s/suite_test.go
app/api/usecase/user/interactor.go
app/api/usecase/user/interactor_test.go

This simplifies the logic of the ConfigMap Watcher functionality that updates CR when the CR templates in ConfigMaps change. The previously applied input fields are now stored within the CRs itself and are re-applied upon update.
This allows for the propagation of MinIO credentials upon update.
MinIO credentials are lost when CR template updates.
Closes #
MinIO credentials are propagated when CR template updates.
Now, CRD and CR require extra field `specs.inputData`

feat(API): [KDL6-276] update CR on configmap change

---

app/api/usecase/project/interactor.go

It has been found (by @Javier Gil ) that the order of MinIO Project Policy creation and MinIO Project User creation is reversed. 
infrastructure/minio-admin tests correct behavior creating policy before user
usecase/project applies the inverse order.
usecase/project to follow the same order: creating policy before user

fix(API): [KDL6-290] fixing minio project creation

---

app/api/usecase/project/interactor.go
app/api/usecase/project/interactor_test.go

The project creator needs to be added as a project member on MinIO.
Project creator has no access to project bucket.
Project creator joins the project on MinIO and thus has access to the project bucket.

fix(API): [KDL6-305] Update project creator's MinIO policy

---

app/ui/src/Components/SettingsMenu/SettingsMenu.module.scss
app/ui/src/Components/SettingsMenu/SettingsMenu.tsx

Show the kubeconfig button even if usertools aren't running. 
Closes #
If the UserTools aren't running a button show with a Tooltip letting know that UserTools are required to access to Kubeconfig config.

feat(app): [KDL6-309] update kubeconfig user menu button

---

hack/README.md
hack/kdlctl.sh
hack/scripts/helmfile/helmfile.yaml
hack/scripts/kdlctl/cmd_minikube.sh
hack/scripts/kdlctl/common_functions.sh

The Helmfile currently points to helm-charts in GitHub, so it must be updated to use OCI in GitLab. Additionally, the startup script (`kdlctl.sh`) should be modified to check for the presence of `GITLAB_TOKEN`, which is required to access the GitLab Container Registry where the Helm chart is stored.
The Helmfile currently points to helm-charts in GitHub: `oci://ghcr.io/konstellation-io/helm-charts/*`
The Helmfile will point to helm-charts in GitLab: `oci://registry.gitlab.intelygenz.com/konstellation-io/helm-charts/*`
Closes KDL6-336

feat(hack): [KDL6-336] configure kdl to use gitlab repository
