helm/kdl-server/templates/app/configmap.yaml, helm/kdl-server/templates/app/deployment.yaml, helm/kdl-server/values.yaml
=> add config.json to the root path of the app ui

app/ui/src/Pages/Project/pages/KG/components/Filters/components/ScoreFilter/ScoreFilter.tsx, app/ui/src/Pages/Project/pages/KG/components/Filters/components/ScoreFilter/components/Thumb/Thumb.module.scss
=> fix: Overlapping the thumbs does not hide the percentage anymore

app/drone-authorizer/index.js
- Sometimes the script fails because is comparing a url ending with "/" like: `http://url/ == http://url`
=> fix: compare urls using the same format

app/ui/public/robots.txt
=> feat: Disallow crawlers to index all the pages

app/ui/src/Graphql/queries/getUsers.graphql, app/ui/src/Graphql/queries/types/GetUsers.ts, app/ui/src/Pages/Project/components/ProjectNavigation/ProjectNavigation.module.scss, app/ui/src/Pages/Users/components/UserList/UserList.module.scss, app/ui/src/Pages/Users/components/UserList/UsersTable.tsx
=> Add username to server users table

app/ui/package.json, app/ui/src/Components/CircledInfoMessage/__snapshots__/CircledInfoMessage.test.tsx.snap, app/ui/src/Components/CopyToClipboard/__snapshots__/CopyToClipboard.test.tsx.snap, app/ui/src/Components/Layout/ActionsBar/__snapshots__/ActionsBar.test.tsx.snap, app/ui/src/Components/Layout/ConfirmAction/__snapshots__/ConfirmAction.test.tsx.snap, app/ui/src/Components/Layout/Page/DefaultPage/__snapshots__/DefaultPage.test.tsx.snap, app/ui/src/Components/Layout/Page/DefaultPage/__snapshots__/Sidebar.test.tsx.snap, app/ui/src/Components/Layout/Panel/__snapshots__/Panel.test.tsx.snap, app/ui/src/Components/LottieShapes/StatusCircle/StatusCircle.test.tsx, app/ui/src/Components/LottieShapes/StatusCircle/__snapshots__/StatusCircle.test.tsx.snap, app/ui/src/Components/Message/__snapshots__/Message.test.tsx.snap, app/ui/src/Components/MessageActionBox/__snapshots__/MessageActionBox.test.tsx.snap, app/ui/src/Components/SiteBar/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap, app/ui/src/Components/SiteBar/components/Breadcrumbs/components/Crumb/__snapshots__/Crumb.test.tsx.snap, app/ui/src/Components/SiteBar/components/ProjectSelector/__snapshots__/ProjectSelector.test.tsx.snap, app/ui/src/Components/SiteBar/components/SectionSelector/__snapshots__/SectionSelector.test.tsx.snap, app/ui/src/Components/Stepper/__snapshots__/Stepper.test.tsx.snap, app/ui/yarn.lock
=> Fix snapshots and coverage

app/ui/src/Pages/NewProject/pages/Information/Information.tsx, app/ui/src/Pages/NewProject/pages/Information/InformationUtils.ts, app/ui/src/Pages/NewProject/pages/RepositoryDetails/components/InternalRepository/InternalRepository.tsx, app/ui/src/Pages/NewUser/NewUser.tsx, app/ui/src/Pages/NewUser/NewUserUtils.ts, app/ui/src/Utils/string.ts
=> fix: Check inputs validations

app/ui/src/Components/SiteBar/components/Breadcrumbs/useBreadcrumbs.tsx
=> feat: Add down arrow icon to the crumbs

app/ui/src/Pages/NewUser/NewUserUtils.ts
=> fix: The new user regex now is working

app/ui/src/Pages/NewProject/pages/Information/InformationUtils.ts
=> feat: The max number of chars allowed in description text area is now 100000

app/ui/src/Components/DescriptionScore/DescriptionScoreUtils.ts, app/ui/src/Constants/routes.ts, app/ui/src/Hooks/useProjectNavigation.tsx, app/ui/src/Pages/Project/panels/UpdateProjectDescription/UpdateProjectDescription.tsx
=> fix: Rename Knowledge Graph to Knowledge Galaxy

app/ui/src/Pages/NewProject/NewProject.module.scss, app/ui/src/Pages/NewProject/pages/Information/Information.module.scss, app/ui/src/Pages/NewProject/pages/Information/Information.tsx, app/ui/src/Pages/NewProject/pages/Summary/Summary.module.scss, app/ui/src/Pages/NewProject/pages/Summary/Summary.tsx, app/ui/src/Pages/Project/Project.module.scss, app/ui/src/Pages/Project/panels/ProjectSettings/components/TabDangerZone/TabDangerZone.module.scss, app/ui/src/Pages/Project/panels/ProjectSettings/components/TabMembers/TabMembers.module.scss, app/ui/src/Pages/Project/panels/ProjectSettings/components/TabMembers/TabMembers.tsx
=> fix: Now you can scroll and see all the content.

app/ui/src/Pages/Project/panels/ProjectSettings/components/ProjectInfo/ProjectInfo.tsx
=> fix: Hide the active from if the last activation date is null

app/ui/src/Utils/string.ts
=> fix: Proposed slug will be truncated at max of 100 chars

kg/server/topics.py
Fixes cutoff paper input and orders correctly by topic relevance.
=> fix kg problems with topic relevace

app/api/infrastructure/graph/schema.resolvers.go
- min words 50, enough words 200. Linear variation between the limits.
=> simple project description quality implementation

app/ui/src/Pages/Project/pages/KG/components/ResourceDetails/ResourceDetails.module.scss
=> fix: Now you can scroll the abstract of a KG resource

app/ui/src/Pages/Project/panels/ProjectSettings/components/TabDangerZone/TabDangerZone.module.scss, app/ui/src/Pages/Project/panels/ProjectSettings/components/TabDangerZone/TabDangerZone.tsx
=> feat: Remove delete box from danger zone

app/ui/src/Components/SiteBar/SiteBar.module.scss, app/ui/src/Components/SiteBar/SiteBar.tsx
=> feat: Remove global search from the site bar

app/ui/src/App.tsx, app/ui/src/Components/SettingsMenu/SettingsMenu.tsx
=> feat: Remove api token page

app/ui/src/Pages/Project/pages/KG/components/ResourceLists/ResourceLists.tsx, app/ui/src/Pages/Project/pages/KG/components/ResourceLists/components/ResourcesList/ResourcesList.tsx, app/ui/src/Pages/Project/panels/KGResults/KGResults.tsx
=> fix: Now you can filter the starred resources as well

app/ui/src/Pages/Project/pages/KG/KG.tsx
=> fix: Show spinner in the kg view when loading

app/ui/src/Pages/Project/ProjectPanels.tsx, app/ui/src/Pages/Project/components/ProjectNavigation/ProjectNavigation.tsx, app/ui/src/Pages/Project/components/ProjectNavigation/components/NavigationButton/NavigationButton.module.scss, app/ui/src/Pages/Project/components/ProjectNavigation/components/NavigationButton/NavigationButton.tsx
- irregular behaviour when using Project Navigation buttons
- KG Viewer shown at Knowledge Galaxy
=> Fix panel issues.

scripts/create_self_signed_cert.sh
close konstellation-io/science-toolkit#135
=> fix: Fix path mkcert CA in MacOS

app/ui/src/Pages/Project/panels/ProjectSettings/components/TabDangerZone/TabDangerZone.tsx
=> feat: Show warning modal when you try to archive a project.

app/ui/src/Pages/ProjectCreation/ProjectCreation.tsx
=> fix: Redirect to the home page when the user reload the project creation page

app/ui/cypress/integration/projects.spec.ts, app/ui/mock-server/src/mocks/projectMock.js, app/ui/src/Components/ProjectsBar/components/ProjectsFilter/ProjectsFilter.tsx, app/ui/src/Components/ProjectsBar/components/ProjectsFilter/__snapshots__/ProjectsFilter.test.tsx.snap, app/ui/src/Components/ProjectsBar/components/ProjectsOrder/ProjectsOrder.tsx, app/ui/src/Components/SiteBar/components/Breadcrumbs/components/Crumb/Crumb.tsx, app/ui/src/Components/SiteBar/components/Breadcrumbs/useBreadcrumbs.tsx, app/ui/src/Components/SiteBar/components/NavigationSelector/NavigationSelector.tsx, app/ui/src/Pages/Projects/components/Project/Project.tsx, app/ui/src/Pages/Users/components/UserList/UsersTable.tsx
=> test: Add e2e testing for the Home page

helm/kdl-server/templates/app/ingress.yaml, helm/kdl-server/templates/app/project-proxy-nginx-config.yaml
=> fix: increase the max body size for filebrowser

app/ui/src/Pages/Project/pages/KG/components/useKGFilters.ts
=> fix: KG show others filter is not working

project-operator/helm-charts/kdlproject/templates/filebrowser/configmap.yml
Add **perm.delete=true** option to entrypoint.sh in `project-operator/helm-charts/kdlproject/templates/filebrowser/configmap.yml`
=> feat: allow users to delete files using filebrowser (Resolves #521) 

app/api/infrastructure/config/config.go, app/api/infrastructure/k8s/usertools.go, helm/kdl-server/templates/app/configmap.yaml, helm/kdl-server/templates/user-tools-operator/kre.konstellation.io_codeservers_crd.yaml, helm/kdl-server/values.yaml
Fixes Oauth2 Proxy image configuration in Usertools CRs
=> fix: Usertools Oauth2 Proxy image config

vscode/Dockerfile, vscode/entrypoint.sh
This PR applies fix changes from release 0.13.1 into the main branch
=> fix(vscode): Change extensions install dir (#597)

.github/workflows/build-release.yml
Fixes the following issues:
* https://github.com/konstellation-io/kdl-server/issues/624
* https://github.com/konstellation-io/kdl-server/issues/623
* https://github.com/konstellation-io/kdl-server/issues/620
=> fix(helm): some image.tag values are not being set on chart release publish

backup/Dockerfile
Just force a new pre release to fix https://github.com/konstellation-io/kdl-server/commit/9f5e2bb084899e63fc3fd9d75ce55c86bdc8e01f
=> ci: Trigger a new prerelease

backup/Dockerfile
- Update base image from `amazon/aws-cli:2.2.45` to `amazon/aws-cli:2.4.0`
=> feat(backup): upgrade aws-cli version in base image

.github/workflows/backup-component-build.yml, .github/workflows/chart-release.yml, .github/workflows/cleaner-component-build.yml, .github/workflows/drone-authorizer-component-build.yml, .github/workflows/gitea-oauth2-setup-component-build.yml, .github/workflows/helm-release.yml, .github/workflows/jupyter-gpu-component-build.yml, .github/workflows/kdl-server-component-build.yml, .github/workflows/mlflow-component-build.yml, .github/workflows/new-release.yml, .github/workflows/project-operator-component-build.yml, .github/workflows/repo-cloner-component-build.yml, .github/workflows/user-tools-operator-component-build.yml, .github/workflows/vscode-component-build.yml
Updating workflow version to `v1.3.1`
=> fix: Update workflow version

.github/workflows/backup-component-build.yml, .github/workflows/cleaner-component-build.yml, .github/workflows/drone-authorizer-component-build.yml, .github/workflows/gitea-oauth2-setup-component-build.yml, .github/workflows/helm-component.yml, .github/workflows/helm-release.yml, .github/workflows/jupyter-gpu-component-build.yml, .github/workflows/kdl-server-component-build.yml, .github/workflows/mlflow-component-build.yml, .github/workflows/new-release.yml, .github/workflows/project-operator-component-build.yml, .github/workflows/repo-cloner-component-build.yml, .github/workflows/user-tools-operator-component-build.yml, .github/workflows/vscode-component-build.yml, ct.yaml, helmlintconf.yaml
Two new features:
- Add helm lint.
- Add helm rc or fix release on chart changes.
=> feat: Update workflow and add helm lint

.github/workflows/backup-component-build.yml, .github/workflows/cleaner-component-build.yml, .github/workflows/drone-authorizer-component-build.yml, .github/workflows/gitea-oauth2-setup-component-build.yml, .github/workflows/helm-component.yml, .github/workflows/helm-release.yml, .github/workflows/jupyter-gpu-component-build.yml, .github/workflows/kdl-server-component-build.yml, .github/workflows/mlflow-component-build.yml, .github/workflows/new-release.yml, .github/workflows/project-operator-component-build.yml, .github/workflows/repo-cloner-component-build.yml, .github/workflows/user-tools-operator-component-build.yml, .github/workflows/vscode-component-build.yml
Change the github workflows version to get the latest monorepo action tag.
=> Fix: Update github workflows version

.github/workflows/backup-component-build.yml, .github/workflows/cleaner-component-build.yml, .github/workflows/drone-authorizer-component-build.yml, .github/workflows/gitea-oauth2-setup-component-build.yml, .github/workflows/helm-component.yml, .github/workflows/helm-release.yml, .github/workflows/jupyter-gpu-component-build.yml, .github/workflows/kdl-server-component-build.yml, .github/workflows/mlflow-component-build.yml, .github/workflows/new-release.yml, .github/workflows/project-operator-component-build.yml, .github/workflows/repo-cloner-component-build.yml, .github/workflows/user-tools-operator-component-build.yml, .github/workflows/vscode-component-build.yml
Update workflows version. This includes the following fix:
- Workaround because `Chart releaser` action doesn't work with tags.
=> fix(workflow): Update workflow versions

helm/kdl-server/templates/drone/ingress.yaml, helm/kdl-server/values.yaml, scripts/kdlctl/cmd_build.sh, scripts/kdlctl/cmd_deploy.sh
We need to increase the Drone ingress nginx body size to allow sending execution results when a job has high duration.
It has been increased to 100 MB.
=> Increase drone ingress body size

.github/workflows/jupyter-gpu-component-build.yml, jupyter-gpu/Dockerfile
Forces new **jupyter-gpu** relase
=> chore(jupyter-gpu): Force release

vscode/Dockerfile
=> chore(vscode): Force release

user-tools-operator/README.md
=> chore(user-tools-operator): Force release

app/ui/src/Components/SiteBar/components/RuntimeSelector/RuntimeItem/RuntimeItem.module.scss, app/ui/src/Components/SiteBar/components/RuntimeSelector/RuntimeSelector.module.scss, app/ui/src/Components/SiteBar/components/RuntimeSelector/RuntimeSelector.tsx, app/ui/src/Pages/Project/panels/RuntimeInfo/RuntimeInfo.module.scss, app/ui/src/Pages/Project/panels/RuntimeInfo/RuntimeInfo.tsx, app/ui/src/Pages/Project/panels/RuntimesList/RuntimeList.module.scss, app/ui/src/Pages/Project/panels/RuntimesList/components/LabelList.module.scss, app/ui/src/Pages/Project/panels/RuntimesList/components/Runtime.module.scss, app/ui/src/Pages/UserKubeconfig/UserKubeconfig.module.scss
Reorganize style that we create or modify during the incorporation of runtimes. This changes doesn't affect the visuals of the UI, just the readability of the code.
=> fix(ui): organize styles

.github/workflows/jupyter-kernelspecs-component-build.yml, helm/kdl-server/values.yaml, jupyter-kernelspecs/Dockerfile
- Adds new workflow for **jupter-kernelspecs** image
- Adds image tag values to helm chart `values.yaml` file
=> chore: Jupyter kernelspecs force release

helm/kdl-server/values.yaml
Bump `enterprise-gateway.kernelspecs.image` to `konstellation/jupyter-kernelspecs:v1.0.0`
=> chore(helm): Bump enterprise-gateway.kernelspecs.image value

.github/workflows/backup-component-build.yml, .github/workflows/cleaner-component-build.yml, .github/workflows/drone-authorizer-component-build.yml, .github/workflows/gitea-oauth2-setup-component-build.yml, .github/workflows/helm-component.yml, .github/workflows/helm-release.yml, .github/workflows/jupyter-gpu-component-build.yml, .github/workflows/kdl-server-component-build.yml, .github/workflows/mlflow-component-build.yml, .github/workflows/new-release.yml, .github/workflows/project-operator-component-build.yml, .github/workflows/repo-cloner-component-build.yml, .github/workflows/user-tools-operator-component-build.yml, .github/workflows/vscode-component-build.yml, app/ui/src/Pages/Project/ProjectContentRoutes.tsx
Fix navigation error found during e2e tests. In some cases the user tools did not allow navigation when runtime is started. This change fix this and makes the code more understandable.
=> fix(ui): fix navigation to user tools when runtime is active.

app/ui/src/Pages/Project/panels/RuntimeInfo/RuntimeInfo.module.scss, app/ui/src/Pages/Project/panels/RuntimeInfo/RuntimeInfo.tsx, app/ui/src/Pages/UserKubeconfig/UserKubeconfig.module.scss, app/ui/src/Pages/UserKubeconfig/UserKubeconfig.tsx
Improve readability and organization of the kube config explanations, in the runtime info panel and in the kubeconfig section.
=> feat: improve kube config instructions

helm/kdl-server/templates/common/backup-cronjob.yaml, helm/kdl-server/values.yaml
=> fix(helm): backup cronjob activeDeadlineSeconds and backoffLimit hardcoded values now are set from values.yaml

app/ui/README.md
Updates UI readme with development instructions, and change format and structure to make it more readable.
=> doc(ui): add development instructions and scripts to readme

app/ui/cypress/integration/runtimes.spec.ts, app/ui/src/Pages/Project/panels/RuntimeInfo/RuntimeInfo.module.scss, app/ui/src/Pages/Project/panels/RuntimeInfo/RuntimeInfo.tsx
We show feedback to the user when the runtime is still being deployed and is not ready yet by adding a loading tag in the runtimeInfo component
closes #751
=> feat(ui): show loading badge when the runtime is in loading status

README.md, helm/kdl-server/Chart.yaml, user-tools-operator/helm-charts/usertools/templates/statefulset.yaml
The generated user-tools now use the serviceAccountName passed from values.
=> fIx: user-tools-operator ServiceAccount name

.github/workflows/helm-release.yml, .pre-commit-config.yaml, jupyter-kernelspecs/kernelspecs/kdl-py3.9-cuda10.2-cudnn7/scripts/kernel-pod.yaml.j2, jupyter-kernelspecs/kernelspecs/kdl-py3.9/scripts/kernel-pod.yaml.j2, user-tools-operator/helm-charts/usertools/templates/statefulset.yaml
This PR modifies the kernelspec j2 definition to include mounting the shared-volume to Jupyter kernels
=> fix(jupyter): Kernels must mount the shared-volume

.github/workflows/helm-release.yml, .pre-commit-config.yaml, jupyter-kernelspecs/kernelspecs/kdl-py3.9-cuda10.2-cudnn7/scripts/kernel-pod.yaml.j2, jupyter-kernelspecs/kernelspecs/kdl-py3.9/scripts/kernel-pod.yaml.j2
=> fix: jupyter kernelspecs shared volume

app/ui/cypress/integration/newProject.spec.ts, app/ui/src/Pages/NewProject/pages/Repository/Repository.tsx, app/ui/src/Pages/NewProject/pages/RepositoryDetails/components/ExternalRepository/ExternalRepository.tsx, app/ui/src/Pages/NewProject/pages/SidebarComponents/Repository/SidebarRepository.tsx
=> feat(ui): disable internal repository option on project creation

helm/kdl-server/values.yaml, jupyter-kernelspecs/kernelspecs/kdl-py3.9-cuda11.6-cudnn8/kernel.json, jupyter-kernelspecs/kernelspecs/kdl-py3.9-cuda11.6-cudnn8/scripts/kernel-pod.yaml.j2, jupyter-kernelspecs/kernelspecs/kdl-py3.9-cuda11.6-cudnn8/scripts/launch_kubernetes.py
This PR adds `konstellation/kdl-py:3.9-cuda11.6-cudnn8` docker image as a kernel spec to `konstellation/jupyter-kernelspecs` image.
=> feat: add kdl-py:3.9-cuda11.6-cudnn8 kernel spec to jupyter-kernelspecs image

app/graphql/schema.graphqls, app/ui/cypress/integration/newProject.spec.ts, app/ui/src/Graphql/client/cache.tsx, app/ui/src/Graphql/client/models/NewProject.ts, app/ui/src/Graphql/types/globalTypes.ts, app/ui/src/Pages/NewProject/pages/RepositoryDetails/components/ExternalRepository/ExternalRepository.module.scss, app/ui/src/Pages/NewProject/pages/RepositoryDetails/components/ExternalRepository/ExternalRepository.tsx
=> feat(ui): add auth method selection on project creation

helm/kdl-server/templates/drone/configmap.yaml, helm/kdl-server/templates/gitea/init-configmap.yaml
Check the issue linked for more information: #838
=> fix(helm): Remove hardcoded passwords

helm/kdl-server/templates/drone/configmap.yaml, helm/kdl-server/templates/drone/serviceaccount-job.yaml, helm/kdl-server/values.yaml
Allow customizing the service account on drone runner jobs. Ref(#842)
=> feat(drone): Use custom service account on drone runner jobs

backup/files/backup-script.sh
Backup CronJob is failing due to a lack of permissions when compressing the `/data/lost+found` folder from the Gitea PVC. This PR excludes that folder from the compressed file that is being uploaded to the Cloud
=> fix(backup): Exclude gitea lost+found dir

backup/files/backup-script.sh
This PR upgrades the backup script in order to cleanup all data stored under the `/backup` folder just before the script finishes
=> feat: cleanup backup storage before finish

helm/kdl-server/templates/_helpers.tpl, helm/kdl-server/templates/app/configmap.yaml, scripts/kdlctl/cmd_deploy.sh
user-tools tls secret name can now be taken from global values if not defined under `userToolsOperator` section
=> feat(helm): get user-tools tls secret name from global

user-tools-operator/helm-charts/usertools/templates/ingress.yaml, user-tools-operator/helm-charts/usertools/values.yaml
This PR adds `spec.ingressClassName` field to **ingress** template which value can be set from `ingress.className` value.
=> feat(user-tools-operator): add ingressClassName to ingress template

scripts/create_nginx_ingress_configmap.sh, scripts/kdlctl/cmd_deploy.sh, scripts/kdlctl/cmd_microk8s.sh, scripts/kdlctl/common_functions.sh
This PR upgrades the local dev environment microk8s version to 1.23
=> refactor(local-dev): upgrade microk8s version to 1.23

README.md
This PR adds new upgrading notes to chart docs
=> doc(helm): add additional upgrading notes for 5.X

project-operator/helm-charts/kdlproject/templates/_helpers.tpl, project-operator/helm-charts/kdlproject/templates/mlflow/ingress.yml, project-operator/helm-charts/kdlproject/values.yaml
This PR adds an ingress template for Mlflow.
=> feat(project-operator): add ingress for mlflow

app/api/infrastructure/k8s/usertools.go
This PR includes the following changes:
* add `spec.repoCloner.mongodbURI` to generated `UserTools`
=> refactor(app): add spec.repoCloner.mongodbURI to generated UserTools

user-tools-operator/helm-charts/usertools/templates/statefulset.yaml
* `tools-secret external` secret access has been removed because it was not being actively used.
=> fix(user-tools-operator): remove tools-secret access

gitea-oauth2-setup/README.md
=> doc(gitea-oauth2-setup): update docs

helm/kdl-server/templates/app/project-proxy-nginx-config.yaml, scripts/create_self_signed_cert.sh, scripts/helmfile/helmfile.yaml, scripts/kdlctl/cmd_deploy.sh
Allow uploading files with spaces.
=> fix(helm): Update proxy conf to allow spaces in files

.github/workflows/backup-component-build.yml, .github/workflows/cleaner-component-build.yml, .github/workflows/drone-authorizer-component-build.yml, .github/workflows/gitea-oauth2-setup-component-build.yml, .github/workflows/helm-component.yml, .github/workflows/helm-release.yml, .github/workflows/jupyter-gpu-component-build.yml, .github/workflows/jupyter-kernelspecs-component-build.yml, .github/workflows/kdl-server-component-build.yml, .github/workflows/mlflow-component-build.yml, .github/workflows/new-release.yml, .github/workflows/project-operator-component-build.yml, .github/workflows/repo-cloner-component-build.yml, .github/workflows/user-tools-operator-component-build.yml, .github/workflows/vscode-component-build.yml
Fix deprecated warnings on GitHub Actions.
=> feat(workflow): Update actions and workflows

project-operator/helm-charts/kdlproject/values.yaml
Fixes project-operator default values
=> fix(project-operator): default values

project-operator/helm-charts/kdlproject/templates/filebrowser/deployment.yml, project-operator/helm-charts/kdlproject/templates/mlflow/deployment.yml, project-operator/helm-charts/kdlproject/values.yaml
Add nodeSelector, affinity and tolerations to kdlprojects
=> feat(project-operator): add nodeSelector, affinity and tolerations

drone-authorizer/.puppeteerrc.cjs, drone-authorizer/Dockerfile, drone-authorizer/package-lock.json, drone-authorizer/package.json
- Upgrade puppeteer to 19.4.0 version.
- Upgrade the locking package file.
- Install some components in the Dockerfile.
=> fix(drone-authorizer): Upgrade puppeteer and fix Dockerfile

.gitignore, scripts/helmfile/helmfile.lock, user-tools-operator/helm-charts/usertools/templates/statefulset.yaml
=> feat(usertools): Mount MinIO secrets from kdl-server secret/cm

scripts/kdlctl/cmd_help.sh
Fix typo in the file cmd_help
Fix typo found in one script file
Maintenance
- [x ] Other changes (ci configuration, documentation or any other kind of changes)
- [x ] I have executed the pre-commit hooks locally.
=> fix(scripts): fix typo in the file cmd_help

app/api/entity/user_activity.go
User registries in MongoDB were not being saved properly. An ID was not being set.
Project delete option was not working properly because of this.
=> fix(kdl-api): fix user registry save

app/api/http/controller/auth.go, app/api/infrastructure/droneservice/service.go, app/api/infrastructure/giteaservice/service.go, app/api/infrastructure/k8s/kdlproject.go, app/api/infrastructure/k8s/kubeconfig.go, app/api/infrastructure/k8s/secret.go, app/api/infrastructure/k8s/service_account.go, app/api/infrastructure/k8s/usertools.go, app/api/infrastructure/minioservice/service.go, app/api/infrastructure/repository/project.go, app/api/infrastructure/repository/runtime.go, app/api/infrastructure/repository/user.go, app/api/usecase/project/interactor.go, app/api/usecase/project/interactor_members.go, app/api/usecase/user/interactor.go, app/api/usecase/user/interactor_users_sync.go, gitea-oauth2-setup/k8s.go, gitea-oauth2-setup/main.go, repo-cloner/cloner/user_repo.go
Replace \"%s\" with %q
Go now supports a better way of adding commas in strings
Cleaner code
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have executed the pre-commit hooks locally.
=> fix(): replace \"%s\" with %q

app/api/templates/basic/README.md.tmpl
=> fix(readme): update PYTHONPATH

helm/kdl-server/templates/app/configmap.yaml
Fix typo on environment variables in configmap
=> fix: configmap template typo

README.md
Add `helmfile init` step to README
=> chore: update installation instructions

.github/workflows/quality-check-kdl-server-api.yml, .github/workflows/quality-check-kdl-server-ui.yml
Add quality checks workflows.
Previous commit was wrong, it was only required to delete sonarcloud stage, nothing more.
=> add quality checks

scripts/helmfile/values/mongodb-database/values.yaml.gotmpl
Upgrade mongo community image version from 4.2.8 to 4.4.4
Image 4.2.8 is no longer available in mongo community image repository
=> build: upgrade mopngo to 4.4.4

.github/workflows/auto-assign.yml, .github/workflows/stale-issues-and-prs.yml, CONTRIBUTING.md
* add contribution DCO, PR, semantic-release, nomenclature...
* update PAT auto-assign
* add stale-issues-pr workflow
* improve documentation
=> docs(readme): [KDL6-62] update contributing with more info

README.md, docs/tools.md
Update documentation
N/A
N/A
N/A
=> docs: [KDL6-62] update multiple files

hack/scripts/helmfile/helmfile.yaml, hack/scripts/helmfile/values/keycloak/values.yaml.gotmpl, hack/scripts/helmfile/values/postgresql/values.yaml.gotmpl
Add `keycloak` and `postgres` for development
N/A
N/A
N/A
=> feat(kdlctl): add keycloak and postgres for development

README.md, vscode/requirements.txt
- Update README with a client dependencies matrix so users can know before upgrading client versions
- Fix: bump packaging to v22.0 so black dependency can be solved 
Closes #
=> fix: 104 add client dependencies matrix and bump packaging version

user-tools-operator/helm-charts/usertools/templates/statefulset.yaml
Fix sharedVolumes with RW instead RO.
Cannot create volumes with RW
Create new volumes with RW
=> fix(user-tools-operator): enable RW on sharedVolumes

CONTRIBUTING.md, app/package.json, backup/package.json, cleaner/package.json, docs/gitflow.md, gitea-oauth2-setup/package.json, mlflow/package.json, package.json, project-operator/package.json, repo-cloner/package.json, user-tools-operator/package.json, vscode/package.json
Prepare all components to use maintenance branches from `hotfix/**` batches.
N/A
From `hotfix/**` branches create hotfix releases from previously releases published.
N/A
=> ci: enable maintenance branches

app/Dockerfile, hack/scripts/helmfile/helmfile.yaml
- Updated Dockerfile for admin UI as build no longer uses templates.
- Updated kdl-local rc version
Closes #
=> fix(kdl-server): update dockerfile for ui and kdl-local version

app/api/http/main.go, app/api/http/middleware/auth.go, app/api/http/middleware/auth_test.go, app/api/http/middleware/devAuth.go, app/api/infrastructure/graph/schema.resolvers.go, app/api/usecase/project/interactor.go, app/api/usecase/project/interactor_members.go, app/api/usecase/project/interactor_test.go, app/api/usecase/user/interactor.go, app/api/usecase/user/interactor_test.go, app/api/usecase/user/interface.go, app/api/usecase/user/mocks_interface.go, hack/scripts/helmfile/values/kdl-local/values.yaml.gotmpl
When creating a new Project in KDL, it fails because it tries to integrate with user in gitea. At the moment, with integration of keycloak, it will fail as user won´t be in gitea. It needs to be removed.
Closes #
=> feat(api): [KDL6-13] remove gitea from create project

hack/scripts/helmfile/helmfile.yaml, user-tools-operator/helm-charts/usertools/templates/statefulset.yaml
Use legacy file to make a workaround to deploy UserTools until we can fix the integration or research another way to integrate with it.
N/A
N/A
=> chore: parametrize template

hack/scripts/helmfile/values/kdl-local/values.yaml.gotmpl
This fixes an error during deploy
=> chore: [KDL6-3] eliminate duplicate mount of configjson 

app/ui/src/Hooks/useProjectNavigation.tsx
VSCode is gonna be deleted.
The link doesn't show.
Closes #
=> feat: [KDL6-162] hide tool vscode

hack/.kdlctl.conf, hack/scripts/helmfile/helmfile.yaml, hack/scripts/helmfile/values/kdl-local/values.yaml.gotmpl, project-operator/helm-charts/kdlproject/templates/filebrowser/configmap.yml
=> feat: minio rollback

repo-cloner/.dockerignore, repo-cloner/Dockerfile, repo-cloner/README.md
The Dockerfile restructuring introduces multi-stage builds to optimize image size, implements explicit version pinning for Alpine packages, enhances security through proper permission handling and non-root user configuration, improves layer caching by reorganizing dependency installation and source code copying, removes unnecessary debug information from the binary through optimized build flags, and streamlines the final stage to include only essential runtime requirements while maintaining full functionality and compatibility with existing deployments.
N/A
=> feat(repo-cloner): [KDL6-207] standarize dockerfile

hack/scripts/helmfile/helmfile.yaml
Upgrade base helm-chart on local
N/A
=> chore(hack): upgrade helm-chart kdl-local version

Makefile, app/api/infrastructure/k8s/service_account_test.go, app/api/infrastructure/k8s/user_ssh_test.go
Fix incorrect makefile commands
Closes #
=> fix(app): amend Makefile

app/Dockerfile, app/api/README.md, app/docker-entrypoint.sh
Implements several Docker best practices, security improvements, reduce image size, improve build efficiency and follow container best practices.
* Monolithic RUN commands leading to unnecessary layer bloat
* Running processes with more privileges than needed
* No proper signal handling through entrypoint script
* Unoptimized build process and large image size (135MB with 119MB potential waste)
* Missing security features like explicit package versions and proper capabilities
* Inefficient cache usage during builds
* Implemented multi-stage builds with optimized layers
* Minimal permissions through capabilities
* Explicit package versions
* Added proper process management through …
=> fix(app): improve Dockerfile

hack/.kdlctl.conf, hack/kdlctl.sh, hack/scripts/helmfile/helmfile.yaml, hack/scripts/helmfile/values/kdl-local/values.yaml.gotmpl, hack/scripts/helmfile/values/keycloak-initial-data/values.yaml.gotmpl, hack/scripts/helmfile/values/mongodb-community-operator/values.yaml.gotmpl, hack/scripts/helmfile/values/mongodb-database/values.yaml.gotmpl, hack/scripts/helmfile/values/mongodb-initial-data/values.yaml.gotmpl, hack/scripts/helmfile/values/mongodb-string-uri/values.yaml.gotmpl, hack/scripts/kdlctl/cmd_build.sh, hack/scripts/kdlctl/cmd_deploy.sh, hack/scripts/kdlctl/cmd_login.sh, hack/scripts/kdlctl/cmd_microk8s.sh, hack/scripts/kdlctl/common_functions.sh
* Clean useless bash function
* Remove useless ENV
* Change MongoDB by mongodb-operator
* Centralize values
* Increase microk8s to 1.30
N/A
N/A
=> chore(hack): [KDL6-224] prepare MacOS deployment

app/api/entity/repository.go, app/api/infrastructure/graph/generated/generated.go, app/api/infrastructure/graph/model/models_gen.go, app/api/infrastructure/graph/schema.resolvers.go, app/api/infrastructure/mongodb/mongo_test.go, app/api/infrastructure/mongodb/project.go, app/api/usecase/project/interactor.go, app/api/usecase/project/interactor_test.go, app/graphql/schema.graphqls, docs/upgrade_guides/INTERNAL_REPO_DEPRECATION.md
Deprecate two unused attributes: authMethod and credentials. These were used during gitea internal repo creation.
Closes #
=> feat(api): [KDL6-234] deprecate authMethod and credentials

app/ui/src/Graphql/client/cache.tsx, app/ui/src/Graphql/client/models/NewProject.ts, app/ui/src/Graphql/types/globalTypes.ts, app/ui/src/Pages/NewProject/pages/RepositoryDetails/components/ExternalRepository/ExternalRepository.tsx, app/ui/src/Pages/Projects/__snapshots__/Projects.test.tsx.snap, app/ui/src/Pages/Projects/components/Project/Project.tsx
Delete authmethod and credentials buttons, update graphql types
Closes #
=> feat(ui): followup, delete authmethod and credentials

app/api/config.yml, app/api/infrastructure/config/config.go, app/api/infrastructure/config/config_test.go
https://intelygenz.atlassian.net/browse/KDL6-202
Remove config.yaml from api file
Closes #
=> feat(api): [KDL6-202] remove api config

app/api/README.md, app/api/infrastructure/graph/generated/generated.go, app/graphql/schema.graphqls, app/ui/README.md, app/ui/src/Graphql/queries/getProjects.ts, app/ui/src/Graphql/queries/types/GetProjects.ts
Add minIO porject access key and secret key to GetProjects graphql query
Closes #
=> feat(app): [KDL6-232] add minio project credentials

app/ui/src/Components/ProjectsBar/ProjectsBar.tsx, app/ui/src/Pages/Projects/Projects.tsx
=> feat(ui): [KDL6-176] viewer cant create projects

app/ui/mock-server/src/mocks/meMock.js, app/ui/src/App.tsx, app/ui/src/Pages/Project/panels/ProjectSettings/ProjectSettings.tsx, app/ui/src/Pages/Project/panels/ProjectSettings/components/TabInfo/TabInfo.tsx, app/ui/src/Pages/Project/panels/ProjectSettings/components/TabMembers/TabMembers.tsx, app/ui/src/Pages/Project/panels/ProjectSettings/components/TabMembers/components/Member/Member.tsx
=> feat(ui): [KDL6-221] viewer cant change project settings

app/ui/mock-server/src/mocks/projectMock.js, app/ui/src/Constants/routes.ts, app/ui/src/Graphql/queries/getProjects.ts, app/ui/src/Graphql/queries/getUserTools.ts, app/ui/src/Graphql/queries/types/GetProjects.ts, app/ui/src/Graphql/queries/types/GetUserTools.ts, app/ui/src/Mocks/entities/project.ts, app/ui/src/Pages/Project/ProjectContentRoutes.tsx, app/ui/src/Pages/Project/components/ProjectToolsRoutes/ProjectToolsRoutes.tsx, app/ui/src/Pages/Projects/components/Project/__snapshots__/Project.test.tsx.snap
remove ToolsUrl.vscode from ui
Closes #
=> feat(ui): [KDL6-259] remove ToolsUrl.vscode from ui

app/api/infrastructure/mongodb/mongo_test.go, app/api/infrastructure/mongodb/user.go
Parse user last_activity
Closes #
=> fix(api): [KDL6-199] parse user last_activity

docs/tools.md
Add go.work disclaimer
Closes #
=> docs: add go.work disclaimer

app/api/README.md, app/api/infrastructure/config/config.go, app/api/infrastructure/config/config_test.go, repo-cloner/config/config.go
Keycloak in config is optional, as it is not called at the moment in any Use Case
Closes #
=> fix(api): [KDL6-279] Set keycloak as optional

app/ui/src/Pages/NewProject/NewProject.tsx, app/ui/src/Pages/Project/ProjectContentRoutes.tsx
=> feat(ui): [KDL6-272] disable popup create project

app/ui/src/Components/SettingsMenu/SettingsMenu.module.scss, app/ui/src/Components/SettingsMenu/SettingsMenu.tsx, app/ui/src/Constants/routes.ts, hack/scripts/helmfile/values/kdl-local/values.yaml.gotmpl
Create logout button in KDL.
Closes #
=> feat(ui): [KDL6-254] sign out

app/Dockerfile, app/api/README.md, app/api/infrastructure/keycloak/mocks_interface.go, app/api/infrastructure/mongodb/mongo_test.go, app/api/infrastructure/mongodb/project.go, app/api/infrastructure/mongodb/user.go, app/api/scripts/minio/sync.go, app/api/scripts/minio/sync_test.go, app/api/scripts/sync_minio_data.go, app/api/usecase/project/interface.go, app/api/usecase/project/mocks_interface.go, app/api/usecase/user/interface.go, app/api/usecase/user/mocks_interface.go
Create script to initialize data in minIO
Closes #
=> feat(hack): [KDL6-273] script to initialize minIO data

hack/scripts/helmfile/helmfile.yaml
update KDL server version to 6.2.2
Closes #
=> chore: update KDL server version to 6.2.2

app/ui/src/Hooks/useProjectNavigation.tsx
=> feat(ui): [KDL6-292] hide knowledge galaxy

app/ui/mock-server/src/mocks/runtimeMock.js, app/ui/src/Pages/Project/components/ProjectNavigation/components/NavElements/NavElements.module.scss, app/ui/src/Pages/Project/components/ProjectNavigation/components/NavElements/NavElements.tsx
=> feat(ui): [KDL6-298] usertool status

hack/.kdlctl.conf, hack/kdlctl.sh, hack/scripts/helmfile/values/kdl-local/values.yaml.gotmpl, hack/scripts/kdlctl/cmd_build.sh, hack/scripts/kdlctl/cmd_dev.sh, hack/scripts/kdlctl/cmd_minikube.sh, hack/scripts/kdlctl/common_functions.sh
Closes [KDL6-289]
This change makes kdl-local run on Linux and macOS
[KDL6-289]: https://intelygenz.atlassian.net/browse/KDL6-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(hack): [KDL6-289] use minikube instead microk8s

hack/kdlctl.sh, hack/scripts/kdlctl/cmd_build.sh, hack/scripts/kdlctl/cmd_help.sh
update kdl command in kdlctl.sh file
Closes #
=> chore(hack): update kdl command in kdlctl.sh file

app/api/README.md, app/api/entity/tool_urls.go, app/api/infrastructure/config/config.go, app/api/infrastructure/config/config_test.go, app/api/infrastructure/graph/generated/generated.go, app/api/infrastructure/graph/schema.resolvers.go, app/graphql/schema.graphqls, app/ui/src/Graphql/queries/getProjects.ts, app/ui/src/Graphql/queries/getUserTools.ts, app/ui/src/Graphql/queries/types/GetProjects.ts, app/ui/src/Graphql/queries/types/GetUserTools.ts, hack/scripts/helmfile/values/kdl-local/values.yaml.gotmpl
Send minio console url and Knowledge Galaxy Enabled value in graphql ToolUrls type
Closes #
=> feat(api): [KDL6-296] update graphql ToolUrls type

app/ui/mock-server/src/mocks/runtimeMock.js, app/ui/src/Components/Icons/RuntimeIcon/RuntimeIcon.module.scss, app/ui/src/Components/Icons/RuntimeIcon/RuntimeIcon.tsx, app/ui/src/Pages/Project/components/ProjectNavigation/components/NavElements/NavElements.module.scss, app/ui/src/Pages/Project/components/ProjectNavigation/components/NavElements/NavElements.tsx
=> feat(ui): [KDL6-298] usertool status 

hack/scripts/helmfile/helmfile.yaml, hack/scripts/kdlctl/cmd_uninstall.sh
Upgrade hack script to remove kdlusertools and kdlprojects
Upgrade kdl-local version in helm chart
Upgrade hack script to remove kdlusertools and kdlprojects
Closes #
=> chore: upgrade kdl-local version in helm chart

app/api/README.md, app/api/http/main.go, app/api/infrastructure/config/config.go, app/api/infrastructure/config/config_test.go, repo-cloner/config/config.go, repo-cloner/config/config_test.go
add flag to enable/disable watcher configmap to configuration
Improve config validation
Closes #
=> feat(app): [KDL6-324] add watcher configmap enable flag

app/api/infrastructure/config/config.go, repo-cloner/config/config.go
=> fix(app): amend logs in config error

app/ui/src/Pages/Users/components/UserFiltersAndActions/UserActions.tsx
=> feat(app): [KDL6-286] sync users button

.github/.golangci.yml, app/api/entity/usertools.go, app/api/infrastructure/graph/generated/generated.go, app/api/infrastructure/graph/schema.resolvers.go, app/api/infrastructure/k8s/interface.go, app/api/infrastructure/k8s/mocks_interface.go, app/api/infrastructure/k8s/pvc.go, app/api/infrastructure/k8s/pvc_test.go, app/api/infrastructure/k8s/suite_test.go, app/api/usecase/user/interactor.go, app/api/usecase/user/interactor_test.go, app/api/usecase/user/interface.go, app/api/usecase/user/mocks_interface.go, app/graphql/schema.graphqls, app/ui/src/Graphql/queries/getMe.ts, app/ui/src/Graphql/queries/getUserTools.ts, app/ui/src/Graphql/queries/types/GetMe.ts, app/ui/src/Graphql/queries/types/GetUserTools.ts, hack/scripts/helmfile/helmfile.yaml, hack/scripts/helmfile/values/initial-resources/values.yaml
Get current storage size user tools
Closes #
=> feat(app): [KDL6-326] get current storage size user tools
